### ISSUE TITLE
Missing Nodes in ddNodes Table

### ISSUE THREAD

**Issue by juame** [K2InformaticsGmbH/imem#160]
During upgrade from IMEM-1.6.3 to IMEM-1.7.0 we had following situation:
* ddNode Table on servers with 1.7.0 contained only the nodes on release 1.7.0
![image](https://user-images.githubusercontent.com/7010789/27428180-8d67163c-5741-11e7-9b20-cad474bd3733.png)
* ddNode Table on servers with 1.6.3 contained all nodes in the IMEM cluster
![image](https://user-images.githubusercontent.com/7010789/27428187-946cc5f8-5741-11e7-8b62-7918f2333128.png)

**Comment by shamis** [comment]
@juame This was mentioned as a known issue in the release document of [sbsgui](https://github.com/K2InformaticsGmbH/sbsgui/blob/1.5.1.050911/docs/ReleaseDocumentation.md#known-issues-and-limitations) and [cpro ](https://github.com/K2InformaticsGmbH/cpro/blob/1.5.1/docs/ReleaseDocumentation.md#known-issues-and-limitations)

> Known issues and limitations
> While upgrading, ddNode table will not show nodes with the previous versions, please refer to 
 ddSchema when verifying the state of the cluster
After the complete cluster upgrade all nodes should also be visible on ddNode

This was because of the time structure change form a 3 tuple to a 4 element tuple
