### ISSUE TITLE
ram mode is not respected when a disc file (db) is present in direcotry

### ISSUE THREAD

**Issue by tgdriph3** [K2InformaticsGmbH/imem#295]
Setup with any application using IMEM (e.g. dderl). Starting from ram mode (means entering cold start) on a system that is down is not respected when a disc file Folder is still present.  Could be related to #216. Please investigate.

cc: @c-bik f.y.i.

**Comment by stoch** [comment]
@tgdriph3 ColdStart support is designed for RAM nodes only. With a disk node, there is no cold start because the data is there already.
Likewise, cold start is skipped if a new node is entering a cluster, again because the data is already there on the other node.
You can delete the database, configure the node to be RAM based and do a cold start then.
To use a cluster snapshot to initialize a disk node today, you need a cluster with one DISK and one RAM node (which you can decomission later).
For development, you can work with a single RAM node which always cold starts (on the latest cluster snapshot). Like this, you get a history of database versions from which you can pick one to start.
